Convert to multiplatform
komputing/KHex pull request #11
Opened 2021-01-14 11:22 UTC by fullkomnun

An attempt to convert the library to Kotlin multiplatform:
- Initially targeting jvm and js
- Part of an effort to convert [KHash](https://github.com/komputing/KHash) and eventually [KEthereum](https://github.com/komputing/KEthereum) following the [previous effort](https://github.com/komputing/KEthereum/pull/63)
targeting Gradle Kotlin DSL 
- Follows the best practices for Kotlin DSL with buildSrc 
Inspired by ["Kotlin Multiplatform And Github Actions"](https://www.adsbynimbus.com/tech-blog/kotlin-multiplatform-and-github-actions) and it's companion [template repo](https://github.com/timehop/kotlin-mpp-template)
- The main issue is that [Jitpack is not compatible with KMP](https://github.com/jitpack/jitpack.io/issues/3853)
and while GitHub Actions can be a great fit for CI, GitHub Packages has [limitations](https://chrynan.codes/github-packages-not-the-right-tool-for-the-job/) that makes it useless for OSS with [no apparent resolution so far](https://github.community/t/download-from-github-package-registry-without-authentication/14407/44)
- Bintray or sonatype/maven central could be alternatives

2021-01-14 16:18 UTC, ligi approved these changes
Thanks!

2021-01-16 20:35 UTC, fullkomnun commented
Enabled strict ['explicitApi'](https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors) mode for all modules

2021-01-16 22:27 UTC, ligi commented
hey - wondering why you closed the PR?

2021-01-16 23:38 UTC, fullkomnun commented
Closed by mistake

2021-01-25 05:02 UTC, fullkomnun commented
Meanwhile, for development purposes, Github Packages may be used as a maven repository that supports Kotlin MP using this ugly workaround(https://github.community/t/download-from-github-package-registry-without-authentication/14407/44). 

Are any changes required in the CO to build Kotlin MP projects?

2021-01-25 07:15 UTC, ligi commented
"CO" ?

2021-01-25 07:18 UTC, fullkomnun commented
> "CO" ?

CI, fixed the typo =]

2021-01-25 07:21 UTC, ligi commented
ah guessed so but was not sure - the CI is just executing gradle commands - but I would also be open to add Github Actions here if this would be easier. I would prefer github packages over maven central / bintray - eve though the workaround looks ugly ..
So far I am only targeting the JVM - but think there is value in supporting Kotlin MP.

2021-01-25 07:34 UTC, fullkomnun commented
Yes, I focus on adding JS(browser, node) as an additional target for my use-case, besides JS is quite popular in the blockchain domain. Other targets such as iOS or other native targets may be added later..

2021-01-25 07:36 UTC, ligi commented
Cool - completely agree that JS would be the most interesting target currently.

2021-01-31 12:35 UTC, fullkomnun commented
By the way, why is the root package 'org.komputing.khex' while the artifact is published under 'com.github.komputing.khex'?

2021-01-31 12:47 UTC, ligi commented
because I do not want to bind to github too much. Really hope in the future we can have something equally user-friendly but decentralized and not in the hand of Microsoft ;-)
Looking at radicle e.g.
github is just the current gateway and involved in deployment. But it is not forever. But I have control over komputing - and this is a constant I do not want to change.
But good thinking! Keep up the good work!!

2021-02-08 16:20 UTC, fullkomnun commented
@ligi The conversion is complete including usage of GitHub Actions workflows:
- Pull Request Check (pr-check.yml): triggered for PRs to master, builds project and runs tests, uploads report in case of failure
- Continuous Integration (continuous-integration.yml) triggered for push to master, builds project and runs tests, uploads report in case of failure and uploads artifacts to GitHub Packages with version of 'master-SNAPSHOT'
- Release (release.yml): triggered for GitHub release creation, builds project and runs tests, uploads report in case of failure and uploads artifacts to GitHub Packages with version according to the release/tag

This allows deploying kotlin multiplatform artifacts to GitHub Packages while also supporting jitpack for jvm-only variant.
You can see this ci in action in [my fork](https://github.com/fullkomnun/KHex).
KHash also already converted and fetches it's KHex multiplatform dependencies from GitHub Packages using this [workaround](https://github.community/t/download-from-github-package-registry-without-authentication/14407/44).
Any maven/gradle project can use the same public credentials from README.md to download the packages.

Before this can be declared 'ready' I need you to perform the [following](https://github.community/t/download-from-github-package-registry-without-authentication/14407/44):
1. Make sure to enable GitHub Actions for the original repository (if not enabled)
2. Create a '[machine user](https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users)' according to these instructions and add it to the repo/organisation as a collaborator/outside-collaborator.
3. Create a PAT with the read:packages scope for that 'machine user'.
4. Run `docker run jcansdale/gpr encode <PAT>`
5. Share the output so I can update the encoded token and READEME.md 
(I did it for my forks but you have to this once for the original repos)

2021-02-15 08:15 UTC, ligi requested changes
Great work - just the repo needs to be changed in some part of the docs. Will do the steps for the machine user you outlined later today.

2021-02-16 14:40 UTC, ligi commented
Sorry it takes a bit longer. The step of creating a user dragged in the need to setup email for komputing.org

2021-02-19 19:52 UTC, ligi commented
@fullkomnun sorry for the delay - here the output:
```
A NuGet `nuget.config` file:
<packageSourceCredentials>
  <github>
    <add key="Username" value="PublicToken" />
    <add key="ClearTextPassword" value="&#57;&#50;&#55;&#52;&#49;&#100;&#56;&#51;&#100;&#54;&#57;&#97;&#99;&#97;&#102;&#49;&#98;&#52;&#97;&#48;&#52;&#53;&#51;&#97;&#99;&#50;&#54;&#56;&#54;&#98;&#54;&#50;&#53;&#101;&#52;&#97;&#101;&#52;&#50;&#98;" />
  </github>
</packageSourceCredentials>

A Maven `settings.xml` file:
<servers>
  <server>
    <id>github</id>
    <username>PublicToken</username>
    <password>&#57;&#50;&#55;&#52;&#49;&#100;&#56;&#51;&#100;&#54;&#57;&#97;&#99;&#97;&#102;&#49;&#98;&#52;&#97;&#48;&#52;&#53;&#51;&#97;&#99;&#50;&#54;&#56;&#54;&#98;&#54;&#50;&#53;&#101;&#52;&#97;&#101;&#52;&#50;&#98;</password>
  </server>
</servers>

An npm `.npmrc` file:
@OWNER:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken="\u0039\u0032\u0037\u0034\u0031\u0064\u0038\u0033\u0064\u0036\u0039\u0061\u0063\u0061\u0066\u0031\u0062\u0034\u0061\u0030\u0034\u0035\u0033\u0061\u0063\u0032\u0036\u0038\u0036\u0062\u0036\u0032\u0035\u0065\u0034\u0061\u0065\u0034\u0032\u0062"
```

2021-02-21 00:38 UTC, fullkomnun commented on README.md
> +        url = uri("https://maven.pkg.github.com/fullkomnun/KHex")
commited

2021-02-21 00:38 UTC, fullkomnun commented on README.md
> +        name = "fullkomnun/KHex GitHub Packages"
commited

2021-02-21 00:39 UTC, fullkomnun commented on README.md
> +![CI](https://github.com/fullkomnun/KHex/workflows/Continuous%20Integration/badge.svg)
commited

2021-02-21 00:47 UTC, ligi approved these changes

2021-02-21 00:48 UTC, merged

2021-02-21 00:54 UTC, fullkomnun commented
Ready to go, if everything goes well - KHash will follow

2021-02-21 01:02 UTC, ligi commented
cool - unfortunately there seems to be a problem with actions: https://github.com/komputing/KHex/runs/1944045614

Was just waiting for my old CI and it was happy - should have waited for the actions also - remembering for next time ..-)

2021-02-21 01:05 UTC, fullkomnun commented
Yes, CI has built and ran tests successfully but publication has failed, although i do see published [artifacts](https://github.com/orgs/komputing/packages?repo_name=KHex) for 'master-SNAPSHOT'. Can you re-run the CI workflow maybe?

2021-02-21 01:19 UTC, ligi commented
cool - yea the rerun worked

2021-02-21 01:24 UTC, fullkomnun commented
And I was able to fetch it from my KHash fork using the credentials so pushed the [changes](https://github.com/komputing/KHash/pull/21). 
Currently though it targets 'master-SNAPSHOT', for it to target a stable release you have to create a new GitHub release. 
Both the old ci/Jitpack and the new GitHub Actions/Packages should work in tandem keeping it backwards-compatible.

2021-02-21 01:36 UTC, ligi commented
Released 1.1.0